# Sample Workflow

## Connect to Qualtrics API

```{r}
## connect using key saved in ~/.qualtrics_api_key
connect_qualtrics("cuboulder")

## connect using some API key passed as string
connect_qualtrics("cuboulder", key = "abcdefghijklmnopqrstuvwxyz")
```

## List Available Surveys

```{r}
## Return DF of surveys to available with API key & Login combo

s_list <- get_surveys()        # Find all surveys available
s_list <- get_surveys("week")  # Find surveys whos name matches "week"
```

## Load Surveys

```{r}
## Load survey metadata from Qualtrics; return survey design object
surveys <- load_survey()                     # load all surveys
surveys <- load_survey("week1-survey")       # load surveys with exact name "week1-survey"
surveys <- load_survey("SV_abcdefghijklmno") # load survey with ID SV_abcdefghijklmno
surveys <- load_survey(s_list)               # load all surveys in DF s_list

surveys <- load_survey("week",
                       match.exact = FALSE) # load all surveys matching "week"

```

## Get survey responses

```{r}
survey1 <- load_survey("week1")    # grab week#1 survey

## Get survey responses as a dataframe
resp <- get_responses(survey1)      # get responses to all questions
resp <- get_responses(survey1,      # get responses to question "Q10"
                      question="Q10")
resp <- get_responses(survey1,      # get responses w/ metadata
                      metadata = TRUE)
```
